name: emergency_system
description: "A secure emergency medical information thesis application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  file_picker: ^11.0.3
  flutter:
    sdk: flutter
  http: ^1.6.0
  http_parser: ^4.1.2
  mobile_scanner: ^7.4.0
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
